### ISSUE TITLE
Enrich data with user input

### ISSUE THREAD

**Issue by maugsbur** [ciudadanointeligente/legislative#84]
Eg:
- [ ] Blog Posts
- [ ] Related resources/documents
- [ ] Forums
- [ ] Annotations
- [x] Tags
- [ ] Citizen approval, urgency, etc.
- [ ] Citizen initiatives, petitions
